config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users, controllers: {
    registrations: 'devise_overrides/registrations',
    omniauth_callbacks: 'devise_overrides/omniauth_callbacks'
  }

  resources :users, only: [:index] do
    resource :profile, only: [:show]
    resources :events, only: [:index], controller: 'users/events'
  end
  resources :meetup_users, only: [:show]

  resources :locations do
    patch :archive, on: :member
  end

  resources :chapters do
    resources :leaders, only: %i[index create destroy], controller: 'chapters/leaders' do
      get :potential, on: :collection
    end

    member do
      get :code_of_conduct_url
    end
  end

  resources :regions do
    resources :leaders, only: %i[index create destroy], controller: 'regions/leaders' do
      get :potential, on: :collection
    end
  end

  resources :organizations, only: %i[index show new create] do
    get :download_subscriptions
  end

  resources :events do
    resources :organizers, only: %i[index create destroy] do
      get :potential, on: :collection
    end
    resources :checkiners, only: %i[index create destroy]
    resources :volunteers, only: [:index]

    scope module: :events do
      resources :students, only: [:index]
      resources :attendees, only: %i[index update]
      resources :attendee_names, only: [:index]
      resources :emails, only: %i[new create show]
      resource :survey, only: [:edit]
    end

    resources :sections, only: %i[create update destroy] do
      post :arrange, on: :collection
    end

    resources :rsvps, except: %i[show index new] do
      get :quick_destroy_confirm

      new do
        get :volunteer
        get :learn
      end

      resources :surveys, only: %i[new create]
    end

    resources :surveys, only: %i[new index] do
      get :preview, on: :collection
    end

    resources :event_sessions, only: %i[index show destroy] do
      resources :checkins, only: %i[index create destroy]
    end

    resources :organizer_tools, only: [:index], controller: 'events/organizer_tools'

    controller 'events/organizer_tools' do
      get :send_survey_email
      get :organize_sections
      get :diets
      get :rsvp_preview
      get :close_rsvps
      get :reopen_rsvps
      post :send_announcement_email
    end

    collection do
      resources :unpublished_events, only: [:index], controller: 'events/unpublished_events' do
        post :publish
        post :flag
      end

      get :feed
      get :past_events
    end

    member do
      get :levels
    end
  end

  resources :external_events, except: [:show]

  resources :courses, except: [:show]

  get '/about' => 'static_pages#about'
  get '/admin_dashboard' => 'admin_pages#admin_dashboard'
  scope :admin_dashboard, controller: :admin_pages do
    get :send_test_email
    get :raise_exception
  end

  get '/style_guide' => 'static_pages#style_guide'
  get '/styleguide', to: redirect('/style_guide')
end

app/controllers/checkiners_controller.rb
# frozen_string_literal: true

class CheckinersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event

  def index
    authorize @event, :edit?
    render_index
  end

  def create
    authorize @event, :edit?
    @rsvp = @event.rsvps.find_by(id: params.fetch(:event_checkiner, {})[:rsvp_id])
    unless @rsvp
      @event.errors.add(:base, 'Please select a user!')
      return render_index
    end

    @rsvp.update_attribute(:checkiner, true)
    redirect_to event_checkiners_path(@event), notice: "#{@rsvp.user.full_name} is now a checkiner for #{@event.title}!"
  end

  def destroy
    authorize @event, :edit?
    @rsvp = @event.rsvps.find(params[:id])
    @rsvp.update_attribute(:checkiner, false)
    redirect_to event_checkiners_path(@event),
                notice: "#{@rsvp.user.full_name} is no longer a checkiner for #{@event.title}!"
  end

  private

  def find_event
    event
  end

  def event
    @event ||= Event.find(params[:event_id])
  end

  def render_index
    @checkiner_rsvps = @event.attendee_rsvps.where(checkiner: true).includes(:user)
    @potential_checkiners = @event.attendee_rsvps.where(checkiner: false).includes(:user)
    render :index
  end
end

app/views/checkiners/index.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, event_organizer_tools_path(@event)) %>

<%= render partial: 'shared/organizer_breadcrumb', locals: {current_page_title: 'Checkiner Assignments'} %>

<%= render 'shared/model_error_messages', model: @event %>

<h3>Potential Checkiners</h3>
<%= render 'shared/user_chooser',
           action: event_checkiners_path(@event),
           select_id: 'event_checkiner',
           foreign_key: 'rsvp_id',
           choices: @potential_checkiners.collect {|rsvp| [ rsvp.user.full_name, rsvp.id ] }
%>

<h3>Assigned Checkiners</h3>
<table class="table">
  <thead>
  <tr>
    <td></td>
    <td>Name</td>
    <td>Email</td>
    <td></td>
  </tr>
  </thead>
  <tbody>
  <% @checkiner_rsvps.each do |rsvp|  %>
      <tr>
        <td class="avatar-column"><%= user_gravatar(rsvp.user) %></td>
        <td><%= rsvp.user.full_name %></td>
        <td><%= rsvp.user.email %></td>
        <td>
        <% if rsvp.user_id != current_user.id %>
            <%= button_to 'Remove', event_checkiner_path(@event, rsvp), method: :delete,
                               form: {style: "margin-bottom : 0;"}, class: "btn btn-mini" %>
        <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>