config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users, controllers: {
    registrations: 'devise_overrides/registrations',
    omniauth_callbacks: 'devise_overrides/omniauth_callbacks'
  }

  resources :users, only: [:index] do
    resource :profile, only: [:show]
    resources :events, only: [:index], controller: 'users/events'
  end
  resources :meetup_users, only: [:show]

  resources :locations do
    patch :archive, on: :member
  end

  resources :chapters do
    resources :leaders, only: %i[index create destroy], controller: 'chapters/leaders' do
      get :potential, on: :collection
    end

    member do
      get :code_of_conduct_url
    end
  end

  resources :regions do
    resources :leaders, only: %i[index create destroy], controller: 'regions/leaders' do
      get :potential, on: :collection
    end
  end

  resources :organizations, only: %i[index show new create] do
    get :download_subscriptions
  end

  resources :events do
    resources :organizers, only: %i[index create destroy] do
      get :potential, on: :collection
    end
    resources :checkiners, only: %i[index create destroy]
    resources :volunteers, only: [:index]

    scope module: :events do
      resources :students, only: [:index]
      resources :attendees, only: %i[index update]
      resources :attendee_names, only: [:index]
      resources :emails, only: %i[new create show]
      resource :survey, only: [:edit]
    end

    resources :sections, only: %i[create update destroy] do
      post :arrange, on: :collection
    end

    resources :rsvps, except: %i[show index new] do
      get :quick_destroy_confirm

      new do
        get :volunteer
        get :learn
      end

      resources :surveys, only: %i[new create]
    end

    resources :surveys, only: %i[new index] do
      get :preview, on: :collection
    end

    resources :event_sessions, only: %i[index show destroy] do
      resources :checkins, only: %i[index create destroy]
    end

    resources :organizer_tools, only: [:index], controller: 'events/organizer_tools'

    controller 'events/organizer_tools' do
      get :send_survey_email
      get :organize_sections
      get :diets
      get :rsvp_preview
      get :close_rsvps
      get :reopen_rsvps
      post :send_announcement_email
    end

    collection do
      resources :unpublished_events, only: [:index], controller: 'events/unpublished_events' do
        post :publish
        post :flag
      end

      get :feed
      get :past_events
    end

    member do
      get :levels
    end
  end

  resources :external_events, except: [:show]

  resources :courses, except: [:show]

  get '/about' => 'static_pages#about'
  get '/admin_dashboard' => 'admin_pages#admin_dashboard'
  scope :admin_dashboard, controller: :admin_pages do
    get :send_test_email
    get :raise_exception
  end

  get '/style_guide' => 'static_pages#style_guide'
  get '/styleguide', to: redirect('/style_guide')
end

app/views/shared/_chapter_select.html.erb
<div>
  <%= f.label :chapter_id, local_assigns[:label] || 'Chapter', class: 'control-label', label: 'org' %>
</div>
<%= f.collection_select(:chapter_id,
                        Chapter.all,
                        :id,
                        :name,
                        {prompt: true}) %>
<script>
  window.whenReady(function () {
    $('#<%= f.object.class.name.underscore %>_chapter_id').select2({width: '100%'});
    <% if local_assigns[:on_open] %>
      $('#<%= f.object.class.name.underscore %>_chapter_id').on('select2:open', function () {
        <%= local_assigns[:on_open].html_safe %>
      });
    <% end %>
  });
</script>

app/views/shared/_checkin_event_sessions.html.erb
<section class='organizer-dashboard-section'>
  <h3>Check in students and volunteers</h3>
  <% @event.event_sessions.each do |session| %>
    <%= render partial: 'shared/organizer_action', locals: {
      path: event_event_session_checkins_path(@event, session),
      icon: 'fa fa-check-square-o',
      text: "Check in for #{session.name}",
      tip: "Check those students and volunteers in! This will make for easy class sorting."
    } %>
  <% end %>
</section>

app/views/shared/_devise_error_messages.html.erb
<div id="error_explanation">
  <h2>
    <%= I18n.t("errors.messages.not_saved",
               count: resource.errors.count,
               resource: resource.class.model_name.human.downcase)
     %>
  </h2>
  <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/shared/_map.html.erb
<div class="<%= local_assigns[:map_class] || 'gmaps4rails_map' %>" id="gmaps4rails_map"></div>
<%
  markers = Gmaps4rails.build_markers(locations) do |location, marker|
    marker.lat location.latitude
    marker.lng location.longitude
    if defined?(infowindow_template)
      marker.infowindow render(infowindow_template, location: location)
    end
  end
%>

<script src="//maps.google.com/maps/api/js?key=AIzaSyAgKf99_jIqJFKdEEllWFZx5xerCzmdMdY&v=3.35&sensor=false&libraries=geometry"></script>
<%= javascript_include_tag 'markerclustererplus/dist/markerclusterer.min.js' %>

<script>
  window.whenReady(function () {
    var handler = Gmaps.build('Google');
    handler.buildMap({provider: {}, internal: {id: 'gmaps4rails_map'}}, function(){
      var markers = handler.addMarkers(<%=raw markers.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      <% if locations.length == 1 %>
      handler.getMap().setZoom(15);
      <% end %>
    });
  });
</script>

app/views/shared/_model_error_messages.html.erb
<% if model && model.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this <%= model.to_model.class.name.underscore.humanize.downcase %> from being saved:</h2>

    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <%= link_to events_path, class: 'app-name' do %>
    <%= image_tag asset_path('logo.svg'), alt: 'Bridge Troll' %>
  <% end %>
  <% if user_signed_in? %>
    <span class="nav-blurb">Found a bug? Or some unexpected behavior? <a href="https://github.com/railsbridge/bridge_troll/issues" target="_blank">Let us know</a>!</span>
  <% end %>
  <ul class="nav navbar-nav header-user-controls">
    <% if user_signed_in? %>
      <li>
        <%= link_to edit_user_registration_path do %>
          <%= gravatar_image_tag(current_user.email, size: 30, style: 'margin-right: 8px;') %>
          <%= current_user.full_name %>
        <% end %>
      </li>
      <li>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn' %>
        </li>
    <% else %>
      <li id="sign_in">
        <%= link_to "Sign In", '#sign_in_dialog', class: "btn sign-in-button", data: sign_in_modal_return_to_params %>
      </li>
      <li>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_organizer_action.erb
<div class='organizer-action'>
  <% options = {
    class: "organizer-action",
    data: { }
  } %>
  <% options[:data][:confirm] = local_assigns[:confirm] if local_assigns[:confirm] %>
  <% options[:class] += ' organizer-action-inline' if local_assigns[:style] == :inline %>
  <% options[:method] = verb if local_assigns[:verb] %>
  <%= link_to path, options do %>
    <div class='organizer-action-button'>
      <i class='<%= icon %>'></i>
      <%= text %>
    </div>
  <% end %>
  <% if defined?(tip) %>
    <div class="organizer-button-tip">
      <%= tip %>
    </div>
  <% end %>
</div>

app/views/shared/_plus_one_disclaimer.html.erb
<p>All workshops on Bridge Troll focus on providing opportunities for under-represented populations in tech. If you are not a member of an underrepresented group, you can only attend as a student if you're the guest of someone who is a member of the workshop's target population. (For example, men can come as the guest of a woman, a straight person can attend as the guest of a gay person, etc.)</p>
<p class="question">If you are not a member of this workshop's target demographic, list the name of the person who is bringing you here: </p>

app/views/shared/_rsvp_actions.html.erb
<div class='rsvp-text'>
  <% if event.waitlisted_volunteer?(current_user) %>
    You are on the volunteer waitlist for this event!
  <% elsif event.volunteer?(current_user) %>
    You are signed up to volunteer for this event!
  <% elsif event.waitlisted_student?(current_user) %>
    You are on the student waitlist for this event!
  <% elsif event.student?(current_user) %>
    You are signed up to attend this event!
  <% end %>
</div>
<% if event.attendee?(current_user) %>
  <%= link_to 'Edit RSVP', edit_event_rsvp_path(event, event.rsvp_for_user(current_user)), class: 'btn' %>
  <%= link_to 'Cancel RSVP', event_rsvp_path(event, event.rsvp_for_user(current_user)), data: {confirm: 'Are you sure you want to cancel your RSVP?'}, method: :delete, class: 'btn' %>
<% end %>
<% if event.no_rsvp?(current_user) %>
  <% if event.open? %>
    <% if event.allow_student_rsvp? %>
      <%= link_to student_attend_button_text(event), learn_new_event_rsvp_path(event), class: 'btn' %>
    <% end %>
    <%= link_to volunteer_attend_button_text(event), volunteer_new_event_rsvp_path(event), class: 'btn' %>
  <% else %>
    <div class='rsvp-text'>RSVPs are closed!</div>
  <% end %>
<% end %>

app/views/shared/_rsvp_actions_unauthenticated.html.erb
<% if event.open? %>
  <% if event.allow_student_rsvp? %>
    <a href="#sign_in_dialog"
       class="btn sign-in-button"
       data-sign-up-return-to="<%= event_path(event) %>"
       data-return-to="<%= if stay_on_event then event_path(event) else learn_new_event_rsvp_path(event) end %>">
      <%= student_attend_button_text(event) %>
    </a>
  <% end %>
  <a href="#sign_in_dialog"
     class="btn sign-in-button"
     data-sign-up-return-to="<%= event_path(event) %>"
     data-return-to="<%= if stay_on_event then event_path(event) else volunteer_new_event_rsvp_path(event) end %>">
    <%= volunteer_attend_button_text(event) %>
  </a>
<% else %>
    <div class='rsvp-text'>RSVPs are closed!</div>
<% end %>

app/views/shared/_sign_in_dialog.html.erb
<div id="sign_in_dialog" class="modal <% unless Rails.env.test? %>fade<% end %>" tabindex="-1" role="dialog" aria-labelledby="sign_in_dialogLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h1>Sign in</h1>
      </div>
      <div class="modal-body">
        <%= render "shared/sign_in", resource: User.new %>
        <%= devise_links(:forgot_password, :confirmation_instructions) %>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>

app/views/shared/_user_chooser.html.erb
<div class="row">
  <div class="col-md-3">
    <%= form_tag(action, method: :post)  do %>
      <%= select(select_id,
                 foreign_key,
                 choices,
                 {include_blank: ''},
                 class: 'form-control') %>
      <script>
        window.whenReady(function () {
          var options = {};
          <% if defined?(url) %>
          _.extend(options, {
            minimumInputLength: 3,
            ajax: {
              url: '<%= url %>',
              dataType: 'json',
              delay: 250,
              processResults: function (data, page) {
                return {
                  results: data
                };
              },
              cache: true
            }
          });
          <% end %>
          var $select = $('#<%= select_id %>_<%= foreign_key %>');
          $select.select2(options);
          $select.change(function () {
            $select.closest('form').find('input[type=submit]').attr({disabled: !this.value});
          });
        });
      </script>
      <%= submit_tag "Assign", class: "btn btn-primary", style: 'margin: 10px 0;', disabled: true %>
    <% end %>
  </div>
</div>

app/views/shared/_welcome.html.erb
<div class="row">
  <div class="welcome-box">
    <div class="welcome-content">
      <div class="troll">
        <%= image_tag asset_path('troll_plus_logo.svg'), alt: '' %>
      </div>
      <div class="welcome-message">
        <h2>Do you want to learn to code with fun people? <%= link_to "Sign up", new_user_registration_path %> and RSVP for an event.</h2>
        <h2>Or, learn more <%= link_to "about Bridge Troll",
                                                      about_path %>.</h2>
        <h2>This is open source software, so feel free to <%= link_to "peruse our code.", "http://www.github.com/railsbridge/bridge_troll" %></h2>
      </div>
    </div>
  </div>
</div>