config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users, controllers: {
    registrations: 'devise_overrides/registrations',
    omniauth_callbacks: 'devise_overrides/omniauth_callbacks'
  }

  resources :users, only: [:index] do
    resource :profile, only: [:show]
    resources :events, only: [:index], controller: 'users/events'
  end
  resources :meetup_users, only: [:show]

  resources :locations do
    patch :archive, on: :member
  end

  resources :chapters do
    resources :leaders, only: %i[index create destroy], controller: 'chapters/leaders' do
      get :potential, on: :collection
    end

    member do
      get :code_of_conduct_url
    end
  end

  resources :regions do
    resources :leaders, only: %i[index create destroy], controller: 'regions/leaders' do
      get :potential, on: :collection
    end
  end

  resources :organizations, only: %i[index show new create] do
    get :download_subscriptions
  end

  resources :events do
    resources :organizers, only: %i[index create destroy] do
      get :potential, on: :collection
    end
    resources :checkiners, only: %i[index create destroy]
    resources :volunteers, only: [:index]

    scope module: :events do
      resources :students, only: [:index]
      resources :attendees, only: %i[index update]
      resources :attendee_names, only: [:index]
      resources :emails, only: %i[new create show]
      resource :survey, only: [:edit]
    end

    resources :sections, only: %i[create update destroy] do
      post :arrange, on: :collection
    end

    resources :rsvps, except: %i[show index new] do
      get :quick_destroy_confirm

      new do
        get :volunteer
        get :learn
      end

      resources :surveys, only: %i[new create]
    end

    resources :surveys, only: %i[new index] do
      get :preview, on: :collection
    end

    resources :event_sessions, only: %i[index show destroy] do
      resources :checkins, only: %i[index create destroy]
    end

    resources :organizer_tools, only: [:index], controller: 'events/organizer_tools'

    controller 'events/organizer_tools' do
      get :send_survey_email
      get :organize_sections
      get :diets
      get :rsvp_preview
      get :close_rsvps
      get :reopen_rsvps
      post :send_announcement_email
    end

    collection do
      resources :unpublished_events, only: [:index], controller: 'events/unpublished_events' do
        post :publish
        post :flag
      end

      get :feed
      get :past_events
    end

    member do
      get :levels
    end
  end

  resources :external_events, except: [:show]

  resources :courses, except: [:show]

  get '/about' => 'static_pages#about'
  get '/admin_dashboard' => 'admin_pages#admin_dashboard'
  scope :admin_dashboard, controller: :admin_pages do
    get :send_test_email
    get :raise_exception
  end

  get '/style_guide' => 'static_pages#style_guide'
  get '/styleguide', to: redirect('/style_guide')
end

app/models/survey.rb
# frozen_string_literal: true

class Survey < ApplicationRecord
  belongs_to :rsvp

  validates :rsvp_id, uniqueness: { message: 'Only one survey response allowed per user.' }
  validates :recommendation_likelihood, allow_blank: true,
                                        numericality: { only_integer: true, greater_than: 0, less_than: 11 }
end

app/controllers/events/surveys_controller.rb
# frozen_string_literal: true

module Events
  class SurveysController < ApplicationController
    before_action :authenticate_user!
    before_action :find_event

    def edit
      authorize @event, :edit?
    end

    private

    def find_event
      @event = Event.find(params[:event_id])
    end
  end
end

app/controllers/surveys_controller.rb
# frozen_string_literal: true

class SurveysController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event
  before_action :find_rsvp, only: %i[new create]

  def new
    authorize @rsvp, :survey?
    @survey = Survey.where(rsvp_id: @rsvp.id).first_or_initialize
    return unless @survey.persisted?

    flash[:error] =
      "It looks like you've already taken this survey! Email your workshop organizer with any other feedback you have."
  end

  def create
    authorize @rsvp, :survey?
    @survey = Survey.new(survey_params)
    @survey.rsvp_id = @rsvp.id

    if @survey.save
      flash[:notice] = 'Thanks for taking the survey!'
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    authorize @event, :edit?
  end

  def preview
    authorize @event, :edit?
    @survey = Survey.new
    @rsvp = Rsvp.new(id: 0)
    @preview = true
    render :new
  end

  private

  def survey_params
    permitted_attributes(Survey)
  end

  def find_event
    @event = Event.find(params[:event_id])
  end

  def find_rsvp
    @rsvp = current_user.rsvps.find_by(event_id: @event.id)
    return if @rsvp

    flash[:error] =
      "It looks like you're trying to take the survey for an event you didn't attend. Maybe you're signed in with the wrong account?"
    redirect_to event_path(@event)
  end
end

app/views/surveys/_results.html.erb
<table class="table survey-results responsive-table">
  <thead>
    <tr>
      <th>What was great?</th>
      <th>What could have been better?</th>
      <% if student_results %>
        <th>Was the class or section you were in appropriate to your skill level?</th>
      <% end %>
      <th>Comments</th>
      <th title="Likelihood to recommend to a friend or colleague">#</th>
    </tr>
  </thead>
  <% surveys.each do |survey| %>
    <tr>
      <td data-label="What was great:"><%= survey.good_things%></td>
      <td data-label="What could have been better:"><%= survey.bad_things %></td>
      <% if student_results %>
        <td data-label="Was the class or section you were in appropriate to your skill level:"><%= survey.appropriate_for_skill %></td>
      <% end %>
      <td data-label="Comments:"><%= survey.other_comments %></td>
      <td data-label="Recommendation likelihood:"><%= survey.recommendation_likelihood %></td>
    </tr>
  <% end %>
</table>

app/views/surveys/index.html.erb
<%= content_for(:header_text, @event.title) %>
<%= content_for(:header_link, event_organizer_tools_path(@event)) %>

<%= render partial: 'shared/organizer_breadcrumb', locals: {current_page_title: 'Survey Results'} %>

<h2>Student Survey Results</h2>
<%= render 'results', surveys: @event.student_surveys, student_results: true %>

<h2>Volunteer Survey Results</h2>
<%= render 'results', surveys: @event.volunteer_surveys, student_results: false %>

app/views/surveys/new.html.erb
<%= content_for(:header_text, @event.title) %>

<%= render 'shared/model_error_messages', model: @survey %>

<% if @preview %>
  <%= render partial: 'shared/organizer_breadcrumb', locals: {current_page_title: 'Survey Preview'} %>
<% end %>

<h2>How was <%= @event.title %>?</h2>

<p>We love feedback, so let us know how things went for you and anything you think we could make better in the future!</p>

<div class="row">
  <div class="col-md-6 survey-form">
    <%= simple_form_for @survey, url: event_rsvp_surveys_path(@event.id, @rsvp.id) do |f| %>
      <%= f.input :good_things, label: "What was great?", readonly: @preview %>

      <%= f.input :bad_things, label: "What could have been better?", readonly: @preview  %>

      <% if @preview || @rsvp.role_student? %>
        <%= f.input :appropriate_for_skill, label: "Was the class or section you were in appropriate to your skill level? <span>Please let us know if you switched sections or classes (or wish you had), and whether your original section/class was too fast, too slow, or something else.</span>".html_safe, readonly: @preview  %>
      <% end %>

      <%= f.input :other_comments, label: "Any other comments?", readonly: @preview  %>

      <%= f.label :recommendation_likelihood, "How likely are you to recommend this workshop to a friend or colleague? (10 is very likely, 1 is unlikely)" %>
      <%= f.select :recommendation_likelihood, (1..10).to_a.reverse, {}, {class: 'form-control', disabled: @preview}  %>
      <% if !@survey.persisted? && !@preview%>
        <%= f.submit "Submit", class: "btn", data: {disable_with: 'Please wait...'} %>
      <% end %>
      <p></p>
      <% if @preview && @event.survey_sent? %>
        <p>Survey has been sent.</p>
      <% elsif @preview %>
        <p><%= link_to 'Send Survey', event_send_survey_email_path(@event), class: "btn", data: {confirm: 'Are you sure?'} %></p>
      <% end %>

    <% end %>
  </div>
</div>